config/routes.rb
Rails.application.routes.draw do
  #resources :issues
  #mount Upmin::Engine => '/admin'
  #resources :users

  root to: 'visitors#index'
  get '/entry' , to: 'entries#new'
  resources 'entries', only: [:new, :create]
  
  devise_for :users, path: '/', path_names: {sign_in: 'login', sign_out: 'logout'}#, skip: [:registrations, :passwords]
  
  namespace :admin, as: false do
    get '/', to: 'base#index', as: :admin

    resources :issues do
      get 'restore', on: :member
    end
  end
end

app/models/entry.rb
class Entry < MailForm::Base

  attribute :author_name,       validate: true
  attribute :author_link,       validate: true
  attribute :author_email,      validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :photo_url,         validate: true
  attribute :photo_description, validate: true
  attribute :nickname,          captcha: true
  
  def headers
    {
      subject: "Новое фото",
      to:      'entry@peoplesphoto.ru',
      from:    %("#{author_name}" <main@peoplesphoto.ru>)
    }
  end
end

app/models/issue.rb
# == Schema Information
#
# Table name: issues
#
#  id         :integer          not null, primary key
#  title      :string
#  number     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  deleted_at :datetime
#

class Issue < ActiveRecord::Base

  has_many :photos, -> {order :id}

  accepts_nested_attributes_for :photos, reject_if: :all_blank, :allow_destroy => true

  validates_presence_of :number
  validate :photo_count

  acts_as_paranoid 

  before_create :destroy_previous_issue #soft deletion with paranoia

  before_restore :destroy_previous_issue

  def destroy_previous_issue
    Issue.last.destroy while Issue.any?
  end


 
  def photo_count
    if self.photos.size != 45
      errors.add(:photos, "Должно быть 45 в выпуске") 
    end 
  end

  

end

app/models/photo.rb
# == Schema Information
#
# Table name: photos
#
#  id          :integer          not null, primary key
#  title       :string
#  url         :string
#  description :text
#  author_name :string
#  author_link :string
#  issue_id    :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Photo < ActiveRecord::Base
  belongs_to :issue

  validates_presence_of :url, :author_name

  
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime
#  updated_at             :datetime
#  name                   :string
#  role                   :integer
#

class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController

  layout "admin"

  before_filter :authenticate_user!
  before_filter :admin_only


  def index
    @issue = Issue.last
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to :back, :alert => "Access denied."
    end
  end
end

app/controllers/admin/issues_controller.rb
class Admin::IssuesController < Admin::BaseController
  before_action :set_issue, only: [:show, :edit, :update, :destroy, :restore]

  respond_to :html

  def index
    @issues = Issue.only_deleted
    respond_with(@issues)
  end

  def show

    respond_with(@issue)
  end

  def new
    @issue = Issue.new
    45.times do
      photo = @issue.photos.build
    end
    respond_with(@issue)
  end

  def edit
    
  end

  def create
    @issue = Issue.new(issue_params)
    flash[:notice] = 'Новый выпуск был успешно создан!' if @issue.save
    respond_with(@issue)
  end

  def update
    @issue.update_attributes(issue_params)
    flash[:notice] = 'Выпуск был успешно отредактирован!' if @issue.update_attributes(issue_params)
    respond_with(@issue)
  end

  def destroy
    @issue.destroy
    redirect_to admin_path
    #respond_with Issue.last
  end

  def restore
    Issue.restore @issue.id, recursive:true
    redirect_to admin_path
  end

  private
    def set_issue
      @issue = Issue.with_deleted.find(params[:id])
    end

    def issue_params
      params.require(:issue).permit(:title, :number, photos_attributes: [:id, :title, :url, :description, :author_name, :author_link, :_destroy])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception



end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  def new
    @entry = Entry.new
  end
  
  def create
    @entry = Entry.new(params[:entry])
    @entry.request = request
    respond_to do |f|
      f.html {redirect_to root_path}
      f.js  {render nothing: true}
    end
    @entry.deliver!
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @issues = Issue.all
    respond_with(@issues)
  end

  def show
    respond_with(@issue)
  end

  def new
    @issue = Issue.new
    respond_with(@issue)
  end

  def edit
  end

  def create
    @issue = Issue.new(issue_params)
    flash[:notice] = 'Issue was successfully created.' if @issue.save
    respond_with(@issue)
  end

  def update
    flash[:notice] = 'Issue was successfully updated.' if @issue.update(issue_params)
    respond_with(@issue)
  end

  def destroy
    @issue.destroy
    respond_with(@issue)
  end

  private
    def set_issue
      @issue = Issue.find(params[:id])
    end

    def issue_params
      params.require(:issue).permit(:title, :number, photos_attributes: [:id, :title, :url, :description, :author_name, :author_link, :_destroy])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :admin_only, :except => :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to :back, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def index
    @issue = Issue.preload(:photos).last
    @entry = Entry.new
  end

  def new_entry
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_issue
    Issue.last
  end

  def current_issue_number
    Issue.last.number
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/admin/base/index.html.haml
.col-sm-12{style:"padding-top:2%;padding-bottom:5%;"}
  %h3.pull-left{style:"padding:0; margin:0;"}
    People's Photo
    .lead.text-muted "И прочее в том же духе, да еще горький мате", Хулио Кортасар.

  %strong.text-right.pull-right.text-primary
    текущий выпуск ##{@issue.number}
    %br
    = @issue.created_at.strftime("%d/%m/%Y")

.col-sm-4
  .bs-callout.bs-callout-success
    %h4 Создать новый выпуск
    = link_to new_issue_path, class: "btn btn-success btn-block" do
      %i.fa.fa-paint-brush.fa-lg
.col-sm-4
  .bs-callout.bs-callout-info
    %h4 Посмотреть текущий
    = link_to issue_path(@issue), class: "btn btn-info btn-block" do
      %i.fa.fa-eye.fa-lg
.col-sm-4
  .bs-callout.bs-callout-warning
    %h4 Редактировать текущий
    = link_to edit_issue_path(@issue), class: "btn btn-warning btn-block" do
      %i.fa.fa-edit.fa-lg




    

app/views/admin/issues/_form.html.haml
= simple_form_for(@issue, defaults: { required: false } ) do |f|
  - if @issue.errors.any?
    #error_explanation
      %h2= "#{pluralize(@issue.errors.count, "error")} prohibited this issue from being saved:"
      %ul
        - @issue.errors.full_messages.each do |msg|
          %li= msg

  %h4 Номер выпуска:
  .form-inline{style:"margin-bottom:20px;"}
    .form-group
      = f.input :number, label: '#', autofocus:true
  
  %table.table.table-bordered.table-hover.photo-table
    %thead{style:"background:#fff;"}
      %tr
        %th #
        %th Url
        %th Автор 
        %th Ссылка на автора
        %th Описание
    
    
    = f.simple_fields_for :photos do |photo|
      = render 'photo_fields', f: photo
      //.links
      //  = link_to_add_association 'add photo', f, :photos

  = f.submit "Сохранить", class: 'btn btn-success btn-block'

     

app/views/admin/issues/_photo_fields.html.haml
%tbody
  %tr
    %th= f.index+1
    
    %td= f.input :url         , label:false
    %td= f.input :author_name , label:false
    %td= f.input :author_link , label:false
    %td= f.input :description , label:false
//= link_to_remove_association "remove photo", f

app/views/admin/issues/edit.html.haml
.col-sm-12
  %h4.lead Редактирование выпуска ##{@issue.number}
  .bs-callout.bs-callout-warning
    
    = render 'form'

app/views/admin/issues/index.html.haml
%h1 Listing issues

%table.table
  %thead
    %tr
      %th ID
      %th Title
      %th Number
      %th
      %th
      %th
      %th
      
  %tbody
    - @issues.each do |issue|

      %tr
        %th= issue.id
        %td= issue.title
        %td= issue.number
        %td= link_to 'Show', issue
        %td= link_to 'Edit', edit_issue_path(issue)
        %td= link_to 'Destroy', issue, :method => :delete, :data => { :confirm => 'Are you sure?' }
        %td= link_to 'Restore', restore_issue_path(issue)

%br

= link_to 'New Issue', new_issue_path

app/views/admin/issues/new.html.haml
.col-sm-12
  %h4.lead 
    Создание нового выпуска
    .small Должно быть 45 фотографий в выпуске. Номер выпуска, url, автор - обязательны для заполнения.
  .bs-callout.bs-callout-success
    
    = render 'form'

  

app/views/admin/issues/show.html.haml
.col-sm-12
  .bs-callout.bs-callout-info
    .pull-right
      = link_to 'Редактировать', edit_issue_path(@issue), class: "btn btn-warning"
 
    %h4 
      Выпуск ##{@issue.number} 
      %small  от #{@issue.created_at.strftime("%d/%m/%Y")} ~ текущий
    
    %hr
    %table.table.table-hover
      %thead
        %tr
          %th #
          %th Фото
          %th Автор 
          %th Описание
      %tbody
      - @issue.photos.each_with_index do |photo, index|
        %tr
          %th #{index+1} 
        
          %td.col-sm-5
            = link_to photo.url, target:"_blank", style:"text-decoration:none;" do
              %img{"data-aload"=>photo.url, class: "img-responsive img-rounded"}
          %td.col-sm-2 
            %strong= link_to photo.author_name, photo.author_link, target:"_blank"
          %td
            %strong= photo.description



= link_to 'Назад', admin_path, class: "btn btn-default"
= link_to 'Редактировать', edit_issue_path(@issue), class: "btn btn-warning"

app/views/entries/create.html.haml
.container
  %h1 Thank you for your message.
  %p We'll get back to you soon.

app/views/entries/create.js.haml
$('#ajax-modal-body').html("= j (render "Thanks!")");

app/views/entries/new.html.haml
.col-sm-4.col-sm-offset-4
  %h3 Пришлите нам фото

  = simple_form_for( @entry ) do |f|
    = f.input :author_name
    = f.input :author_link
    = f.input :author_email
    = f.input :photo_url
    = f.input :photo_description, as: :text
    .hidden
      =f.input :nickname, hint: "оставьте поле пустым!"

    =f.button :submit

app/views/issues/index.html.haml
%h1 Listing issues

%table
  %thead
    %tr
      %th Title
      %th Number
      %th
      %th
      %th
      
  %tbody
    - @issues.each do |issue|
      %tr
        %td= issue.title
        %td= issue.number
        %td= link_to 'Show', issue
        %td= link_to 'Edit', edit_issue_path(issue)
        %td= link_to 'Destroy', issue, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Issue', new_issue_path

app/views/issues/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @issue.title
%p
  %b Number:
  = @issue.number

= link_to 'Edit', edit_issue_path(@issue)
\|
= link_to 'Back', issues_path

app/views/layouts/_about_modal.html.haml
#aboutModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "aboutModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true",style:"color:#fff;"} ×
        %h4#myModalLabel.modal-title О проекте
      .modal-body
        %p
          People's Photo - это журнал, посвященный фотоработам людей, которых объединяет любовь к фотографии. Здесь каждые полмесяца выходит новый номер. Авторами фотографий становятся сами читатели - отправить фото может любой желающий. Главное, чтобы Ваша фотография была не повседневной, красивой, была фотографией, которой хочется делится. Она должна завораживать.
        %p
          Журнал будет интересен людям, которые занимаются фотосъемкой, хотят наблюдать и просто любят нечто красивое. Тут можно найти описание к работам, в том числе, на что и как была сделана конкретная фотография. Для авторов - это хорошая возможность показать людям, каким должно быть фото.

      .modal-footer
      -#  %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} ×
    

app/views/layouts/_add_photo_modal.html.haml
#addPhotoModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "addPhotoModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true",style:"color:#fff;"} ×
        %h4#myModalLabel.modal-title Отправить фото
      .modal-body#ajax-modal-body

        = simple_form_for @entry, remote:true, html:{'data-toggle'=>'validator',role:"form"}, defaults: { required: false } do |f|
          = f.input :author_name  ,label: "Представьтесь"        ,placeholder: "Ваше имя/никнейм", input_html:{required:true}
          = f.input :author_link  ,label: 'Где найти ваши работы',placeholder: "Ссылка на ваш профиль", input_html:{required:true}
          = f.input :author_email ,label: 'Обратная связь'       ,placeholder: "Email", input_html:{required:true} 
          = f.input :photo_url    ,label: 'Ссылка на фотографию' ,placeholder: "http://cs621524.vk.me/v621524874/5f30/SyqyTYGQwBg.jpg", input_html:{required:true}
          = f.input :photo_description, as: :text, label: "Описание", placeholder: "Кратко опишите где и как вы сделали свое фото, на какую камеру, обрабатывали вы его, возможно, если вы укажете параметры при которых была сделана фотография, мы с радостью их укажем.", input_html:{required:true, rows: 3}
          .hidden
            =f.input :nickname, hint: "оставьте поле пустым!"
          .modal-footer
            =f.button :submit, "Отправить", id: '#ajax-submit', data: {disable_with: "Отправляю.."}

app/views/layouts/_bottom.html.haml
#cd-nav
  .cd-nav-trigger
    %i.fa.fa-bars
    
  %nav#cd-main-nav
    .container
      %ul.list-inline
        %li
          = link_to '#', {"data-target" => "#aboutModal", "data-toggle" => "modal", :type => "button"} do
            О журнале
        %li 
          |
        %li
          = link_to "#", {"data-target" => "#addPhotoModal", "data-toggle" => "modal", :type => "button"} do
            Отправить фото
        %li 
          |
        %li
          = link_to '#', {"data-target" => "#faqModal", "data-toggle" => "modal", :type => "button"} do
            FAQ
        %li
          |
        %li
          = link_to '#', {"data-target" => "#copyrightsModal", "data-toggle" => "modal", :type => "button"} do
            Авторские права
        
      
        %li
          %input#test(data-slider-id='testSlider' type='text' data-slider-min='1' data-slider-max='45' data-slider-step='1' )

app/views/layouts/_copyrights_modal.html.haml
#copyrightsModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "copyrightsModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true",style:"color:#fff;"} ×
        %h4#myModalLabel.modal-title Авторские права
      .modal-body
        %p
          Ваши фотографии будут использоваться редакцией только в пределах журнала People's Photo, и его представительств (официальная группа в VK например), работы размещаются на портале только с указанием авторства. После того как Вы отправили фото, мы можем связаться с вами в сети, которую Вы указали, для подтверждения авторства материала.
        %p  
          К сожалению, бывают и обманщики, которые могут прислать не свою работу, журнал не может на 100% противостоять таким людям, даже не смотря на систему контроля фото контента. К сожалению, ответственность за действия мошенников журнал не несет.
        %p  
          Если вы вдруг увидели свою работу, подписанную чужим авторством, напишите нам на почту itsmyphoto@peoplesphpto.ru, укажите фотографию, Ваш профиль, приложите оригинал фото (приложение файла (архива) с фотографией оригинального расширения сделает рассмотрение Вашей заявки быстрее)и что Вы хотите сделать: изменить авторство и отредактировать описание фото или немедленно удалить фото-работу из журнала. Спасибо за сотрудничество!

      .modal-footer
      -#  %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} ×
    

app/views/layouts/_faq_modal.html.haml
#faqModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "faqModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true",style:"color:#fff;"} ×
        %h4#myModalLabel.modal-title FAQ
      .modal-body
        %p
          Здесь будут популярные вопросы, у нас их пока нет.
          %br
          Если у Вас возникли вопросы, вы можете задать их нам по почте - 
          %br
          .text-center{style:"font-size:20px;"}
            = link_to 'help@peoplesphoto.ru', 'mailto:help@peoplesphoto.ru'
          

      .modal-footer
      -#  %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} ×

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to admin_path, class: 'navbar-brand' do
        %i.fa.fa-home.fa-lg.text-primary
        
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li= link_to 'ТЕКУЩИЙ', current_issue
        %li= link_to 'НОВЫЙ', new_issue_path
        %li.divider-vertical
        %li.disabled= link_to 'АРХИВ', '#'
      %ul.nav.navbar-nav.navbar-right
        %p.navbar-text 
          Выпуск ##{current_issue.number},
          #{time_ago_in_words current_issue.created_at} назад
        %li 
          = link_to root_path do
            НА САЙТ
            
        %li.divider-vertical
        - if user_signed_in?
          -#%li= link_to 'Edit account', edit_user_registration_path
          %li 
            = link_to destroy_user_session_path, :method=>'delete' do
              ВЫЙТИ
              %i.fa.fa-sign-out.text-danger 
        - else
          %li
            = link_to new_user_session_path do
              ВОЙТИ
              %i.fa.fa-sign-in.fa-lg.text-primary
          -#%li= link_to 'Sign up', new_user_registration_path
        

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Photo'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Photo'}"}
    :javascript
      function aload(a){"use strict";a=a||window.document.querySelectorAll("[data-aload]"),void 0===a.length&&(a=[a]);var b,c=0,d=a.length;for(c;d>c;c+=1)b=a[c],b["LINK"!==b.tagName?"src":"href"]=b.getAttribute("data-aload"),b.removeAttribute("data-aload");return a}
    :javascript
      window.onload = function () {
        aload();
      };
    :css
      [data-aload] { background-image: none !important; }

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true

    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body.admin
    - if current_user
      %header
        = render 'layouts/navigation'
    
    .container#content
      .row
        .col-sm-6.col-sm-offset-3      
          = render 'layouts/messages'
        = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title People's Photo - журнал о фотографии 
    -#content_for?(:title) ? yield(:title) : 'Photo'
    %meta{content: "initial-scale=1.0,user-scalable=no,maximum-scale=1,width=device-width", name: "viewport"}
    %meta(http-equiv="content-type" content="text/html" charset="utf-8")
    %meta(http-equiv="x-ua-compatible" content="ie=edge,chrome=1")
    %meta{name:"description", content: "People's Photo - это современный журнал о фотографии. Место, где можно показать свои работы миру."}
    %meta(name="author" content="Винцент Илинич")
    -#{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Photo'}"}
    -# Fix for iPhone 5 fullscreen web apps
    %meta(name="viewport" content="initial-scale=1.0,user-scalable=no,maximum-scale=1" media="(device-height: 568px)")
    %meta(name='apple-mobile-web-app-capable' content='yes')
    %meta(name='apple-mobile-web-app-status-bar-style' content='black-translucent')
    -#OPEN GRAPH
    %meta(content="People's Photo" property='og:title')
    %meta(content="People's Photo - это журнал, посвященный фотоработам людей, которых объединяет любовь к фотографии. Здесь каждые пол-месяца выходит новый номер журнала. Авторами фотографий становятся сами читатели, отправить фото может любой желающий. Журнал будет интересен людям, которые занимаются фотосъемкой, хотят наблюдать и просто любят нечто красивое." property='og:description')
    %meta(content="#{current_issue.photos.first.url}" property='og:image')
    
    = favicon_link_tag 'favicon.ico'
    :javascript
      function aload(a){"use strict";a=a||window.document.querySelectorAll("[data-aload]"),void 0===a.length&&(a=[a]);var b,c=0,d=a.length;for(c;d>c;c+=1)b=a[c],b["LINK"!==b.tagName?"src":"href"]=b.getAttribute("data-aload"),b.removeAttribute("data-aload");return a}
    :javascript
      window.onload = function () {
        aload();
      };
    :css
      [data-aload] { background-image: none !important; }
    
    = stylesheet_link_tag 'application', media: 'all'#, 'data-turbolinks-track' => true

    = javascript_include_tag 'application'
    = csrf_meta_tags

    = javascript_include_tag "//cdn.jsdelivr.net/jquery.mcustomscrollbar/3.0.6/jquery.mCustomScrollbar.concat.min.js"
    = stylesheet_link_tag "//cdn.jsdelivr.net/jquery.mcustomscrollbar/3.0.6/jquery.mCustomScrollbar.min.css"

  

  %body
    .loader-container
      .preloader.loading
        %span.slice
        %span.slice
        %span.slice
        %span.slice
        %span.slice
        %span.slice
      %br
      %h3 
        People's Photo
        .lead журнал о фотографии
    
    .main
      .logo
        %h1.title
          =link_to root_path do 
            People's Photo
        %h4.issue-date
          Журнал о фотографии
          .small
            выпуск №#{current_issue_number}
            
        
      = yield
      = button_tag "", class: "flex-prev" 
      = button_tag "", class: "flex-next" 
      = render 'layouts/bottom'
      = render 'layouts/add_photo_modal'
      = render 'layouts/about_modal'
      = render 'layouts/faq_modal'
      = render 'layouts/copyrights_modal'

app/views/users/_user.html.haml
%td
  = link_to user.email, user
%td
  .sa
    = form_for(user) do |f|
      .form-group
        = f.label :role, "Role:"
        = f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}, class: 'form-control') 
        = button_tag type:"submit", class: "btn btn-success btn-xs" do
          %i.glyphicon.glyphicon-trash

%td
  - unless user == current_user
    = link_to user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-danger btn-sm' do 
      %i.glyphicon.glyphicon-trash

app/views/users/index.html.haml
.container
  .row
    %h3 Users
    .column
      %table.table
        %thead
          %tr
            %th User
            %th Change role

        %tbody
          - @users.each do |user|
             
            %tr  
              = render user

app/views/users/show.html.haml
%h3 User
%p
  Name: #{@user.name if @user.name}
%p
  Email: #{@user.email if @user.email}